{
 "title": "Solax",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "limit_condition",
    "label": "limit_condition",
    "query": "rec_datetime between date_sub(now(),INTERVAL 2 day) and now();"
   },
   {
    "name": "limit_condition2",
    "label": "limit_condition2",
    "query": "from_unixtime(rec_datetime) between < $__from and rec_datetime <  $__to"
   }
  ]
 },
 "panels": [
  {
   "title": "R-Grid",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select grid_voltage_r, uploadTime as `time`\nfrom solax.solax_local\nwhere uploadTime > now(3) - INTERVAL 2 MINUTE\norder by uploadTime desc\nlimit 1\n;\n"
    }
   ]
  },
  {
   "title": "Inverter Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select inverter_status, uploadTime as `time`\nfrom solax.solax_local\nwhere uploadTime > now(3) - INTERVAL 2 MINUTE\norder by uploadTime desc\nlimit 1\n;\n"
    }
   ]
  },
  {
   "title": "Total Daily Yield",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 0 },
   "format": "kwatt",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select total_yield as self_use,uploadDate as `time`\nFROM solax.solax_daily\nWHERE $__timeFilter(uploadDate)\n"
    }
   ]
  },
  {
   "title": "Self Use",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 0 },
   "format": "kwatt",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select (total_yield-feed_in) as self_use,uploadDate as `time`\nFROM solax.solax_daily\nWHERE $__timeFilter(uploadDate)\n"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "select battery_capacity as \"Available\"  , uploadTime as `time`\nfrom solax.solax_local \norder by uploadTime desc\nlimit 1\n"
    }
   ]
  },
  {
   "title": "SOLAR PANELS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select dc_solar_power, uploadTime as `time`\nfrom solax.solax_local\nwhere uploadTime > now(3) - INTERVAL 2 MINUTE\norder by uploadTime desc\nlimit 1\n;\n"
    }
   ]
  },
  {
   "title": "GRID",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select feed_in_power, uploadTime as `time`\nfrom solax.solax_local\nwhere uploadTime > now(3) - INTERVAL 2 MINUTE\norder by uploadTime desc\nlimit 1\n;\n"
    }
   ]
  },
  {
   "title": "S-Grid",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 2 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select grid_voltage_s, uploadTime as `time`\nfrom solax.solax_local\nwhere uploadTime > now(3) - INTERVAL 2 MINUTE\norder by uploadTime desc\nlimit 1\n;\n"
    }
   ]
  },
  {
   "title": "Count Down",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 2 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select time_count_down, uploadTime as `time`\nfrom solax.solax_local\nwhere uploadTime > now(3) - INTERVAL 2 MINUTE\norder by uploadTime desc\nlimit 1\n;\n"
    }
   ]
  },
  {
   "title": "Daily FeedIn",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 2 },
   "format": "kwatt",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \tfeed_in  as feedinenergy, uploadDate as `time`\nFROM solax.solax_daily\nWHERE $__timeFilter(uploadDate)\n;"
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select (inverter_ac_power-feed_in_power) as Consumption, uploadTime as `time`\nfrom solax.solax_local\nwhere uploadTime > now(3) - INTERVAL 2 MINUTE\norder by uploadTime desc\nlimit 1\n;\n"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select battery_power, uploadTime as `time`\nfrom solax.solax_local\nwhere uploadTime > now(3) - INTERVAL 2 MINUTE\norder by uploadTime desc\nlimit 1\n;\n"
    }
   ]
  },
  {
   "title": "T-Grid",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select grid_voltage_t, uploadTime as `time`\nfrom solax.solax_local\nwhere uploadTime > now(3) - INTERVAL 2 MINUTE\norder by uploadTime desc\nlimit 1\n;\n"
    }
   ]
  },
  {
   "title": "Daily Grid Consumption",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 4 },
   "format": "kwatt",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \t(max(consumeenergy) - min(consumeenergy))  as consumeenergy, uploadTime as `time`\nFROM solax.solax_local\nWHERE $__timeFilter(uploadTime)\n"
    }
   ]
  },
  {
   "title": "Solar Panels - LOCAL",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "watt", "label": "Power Consumtion" }
   ],
   "targets": [
    {
     "rawSql": "select `battery_capacity` as \"Battery Charge\"  , uploadTime as `time`\nfrom solax.solax_local\n\n"
    },
    {
     "rawSql": "select `feed_in_power` as \"Grid\"  , uploadTime as `time`\nfrom solax.solax_local\n\n"
    },
    {
     "rawSql": "select `dc_solar_power` as \"Solar\", uploadTime as `time`\nfrom solax.solax_local\n\n"
    },
    {
     "rawSql": "select `battery_power` as \"Battery\", uploadTime as `time`\nfrom solax.solax_local\n\n"
    },
    {
     "rawSql": "select (inverter_ac_power-feed_in_power) as \"Consumption\", uploadTime as `time`\nfrom solax.solax_local"
    }
   ]
  },
  {
   "title": "Yearly Solar Production",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "rawSql": "select sum(total_yield-feed_in) as Self_Use, uploadDate as `time`\nfrom solax.solax_daily\ngroup by year(uploadDate), month(uploadDate)"
    },
    {
     "rawSql": "select sum(feed_in) as Feed_In, uploadDate as `time`\nfrom solax.solax_daily\ngroup by year(uploadDate), month(uploadDate)"
    },
    {
     "rawSql": "SELECT \t(max(consumeenergy) - min(consumeenergy))  as From_Grid, DATE_SUB(LAST_DAY(uploadTime),INTERVAL DAY(LAST_DAY(uploadTime))-1 DAY) as `time`\nFROM solax.solax_local\ngroup by year(uploadTime), month(uploadTime)\n;\n"
    }
   ]
  },
  {
   "title": "Monthly Solar Production",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "rawSql": "select (total_yield-feed_in) as \"Self Use\", uploadDate as `time`   \nfrom solax.solax_daily\n;"
    },
    {
     "rawSql": "select feed_in as \"Feed In\", uploadDate as `time`   \nfrom solax.solax_daily\n;\n\t"
    }
   ]
  },
  {
   "title": "EPS Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "watt", "label": "Power Consumtion" }
   ],
   "targets": [
    {
     "rawSql": "select `peps1` as \"EPS 1\"  , uploadTime as `time`\nfrom solax.solax_stats\n\n"
    },
    {
     "rawSql": "select `peps2` as \"EPS 2\"  , uploadTime as `time`\nfrom solax.solax_stats\n\n"
    },
    {
     "rawSql": "select (`peps3`) as \"EPS 3\", uploadTime as `time`\nfrom solax.solax_stats\n\n"
    },
    {
     "rawSql": "select (`peps3`+`peps2`+`peps1`) as \"EPS Total\", uploadTime as `time`\nfrom solax.solax_stats\n\n"
    }
   ]
  }
 ]
}